# Generated by Django 5.0.4 on 2024-05-25 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(default=0, max_length=100)),
                ('productName', models.CharField(default='no name yet', max_length=100)),
                ('description', models.TextField(default='no description yet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(default='none', max_length=100)),
                ('dim_x', models.IntegerField(default=0)),
                ('dim_y', models.IntegerField(default=0)),
                ('metric', models.CharField(default='na', max_length=2)),
                ('metric2', models.CharField(default='na', max_length=2)),
                ('capacity', models.IntegerField(default=0)),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
