# Generated by Django 3.2.12 on 2024-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='no description yet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(default='no name yet', max_length=100),
        ),
    ]
