# Generated by Django 3.2.12 on 2024-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240519_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metric2',
            field=models.CharField(default='ml', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(default='0', max_length=15),
        ),
    ]
