# Generated by Django 3.2.12 on 2024-05-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240521_1402'),
        ('api', '0009_alter_category_name'),
    ]

    operations = [
    ]
